#!/bin/env bash
# transfers file to server

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	path=$1
	ip=$2
	user=$3
	ssh_path=$4
	scp -o StrictHostkeyChecking=no -i "$ssh_path" "$path" "$user@$ip":~
fi	

