#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it
# Password gotten from the command-line argument
MYSQL_PASSWORD="$1"

# The format for filename backup
FILE_NAME="$(date +"%d-%m-%Y").tar.gz"

# Compresses databases and dumps the MYSQL databases
mysqldump --user=root --password="$MYSQL_PASSWORD" --all-databases > backup.sql
tar -czf "$FILE_NAME" "backup.sql"
